### ISSUE TITLE
New installation path (Eclipse Temurin [Adoptium] or IBM Semeru) not automatically detected

### ISSUE THREAD

**Issue by Markus-Go** [tushev/aojdk-updatewatcher#28]
**Describe the bug**
The new installation paths after the migration from AdoptOpenJDK binaries to Eclipse Foundation are not automatically detected any more.

After upgrade, new JRE/JDK are installed to:
C:\Program Files\Eclipse Foundation

**I'm sure that it's not a 'known-not-a-bug'**
**See**: https://github.com/tushev/aojdk-updatewatcher/wiki/Known-not-a-bugs
[X] Yes

**To Reproduce**
1. Update your JREs/JDKs to latest version
2. Observe that they are not in the list anymore

**Expected behavior**
Installed versions should be detected

**Desktop (please complete the following information):**
 - App Version [e.g. 2.0.2]

**Comment by tushev** [comment]
Thank you for your report! 

Version 2.0.2 supports only AdoptOpenJDK releases. Full support for Adoptuim/Eclipse Temurin builds will be added in version 2.0.3, which is currently being developed.

As a temporary fix, you can manually add the new installations into the list, and remove them when 2.0.3 becomes available.

**Comment by tushev** [comment]
Version 2.0.3 is live, please check it. If there's something wrong with it, please reopen the bug.

**Comment by Markus-Go** [comment]
I am having a problem for Eclipse Temurin JDK 8.0.302-8-hotspot.
For Windows there exists a version jdk8u302-b08.1, which is installed and the updater tries to update to it nevertheless. It thinks, only jdk8u302-b08 is installed.

**Comment by tushev** [comment]
Unfortunately, the metadata that is shipped with `8.0.302+8.1` release identifies it as `8.0.302+8`, hence the update loop. This is not a bug in Update Watcher for AdoptOpenJDK.

The Adoptium team [is aware of this issue](https://github.com/adoptium/installer/issues/337) and hopefully it would be fixed in next releases.

In the meanwhile, just click **Skip this release** for `jdk8u302-b08.1` **after** you've installed it (on the second update suggestion)
