### ISSUE TITLE
Updates change custom directory setting

### ISSUE THREAD

**Issue by Markus-Go** [tushev/aojdk-updatewatcher#3]
First of all, thanks for this great tool! It really compensates a major disadvantage of Adopt OpenJDK!

My issue:
I have installed an Adopt OpenJDK in a custom path (C:\Program Files\Java\jdk-11) and added that manually to the List. When I update the installation, the updates go into the default directory (C:\Program Files\AdoptOpenJDK\jdk-11.0.9.11-hotspot). Then I have two installations all of a sudden, including the old one.

Is it possible when having a custom path to update this location?

Thanks!

**Comment by tushev** [comment]
Hello!

No, manually-added paths should also be managed manually in the list.

However, you possibly could:
- when updating AdoptOpenJDK itself (running MSI install), you could set `C:\Program Files\Java\jdk-11` as a target path for update as well
- if you have only one JDK on your machine, you could add JAVA_HOME instance to the list (instead of custom path), provided that you turn the corresponding feature on during installation of AdoptOpenJDK
- use automatic detection only, unless you don't need to change release settings. It's pretty robust, so it will handle your issue with ease (provided that AdoptOpenJDK itself correctly removes old versions)

**Comment by Markus-Go** [comment]
Hi,

Thanks for your help!

>     * when updating AdoptOpenJDK itself (running MSI install), you could set `C:\Program Files\Java\jdk-11` as a target path for update as well

Actually I missed the part in the MSI installer to change the directory (back) to my custom setting .. you are right, this is still possible. 
However --maybe as an enhancement-- it would be nice if you update an existing installation that it ends up in the same directory as the original one. I think that is the default behaviour of most programs and an expected behaviour by most users... At least I was confused to have two installations (old and new) after an upgrade ;)
Wouldn't it be possible to pass the TARGETDIR to the MSI installer in case of an update?

**Comment by tushev** [comment]
@Markus-Go, the whole concept of my updater is to be as less intrusive as possible. 
> if you update an existing installation that it ends up in the same directory as the original one

I agree that this is "more expected" behavior, but it's up to AdoptOpenJDK to decide (and implement in their MSIs). I think you should create a ticket in https://github.com/AdoptOpenJDK/openjdk-support/issues and ask them, so all users will get correct paths with updates, whether they use my updater or update manually.

P.S. May I ask, why do you add installation manually, and do not rely on automatic discovery of installations?

**Comment by Markus-Go** [comment]
The automatic discovery does not discover my old installation via the registry -- so I had to add it manually.
The version is 11.0.0 (from 2018) and the custom path was C:\Program Files\Java\jdk-11

I just checked again: after the manual upgrade (now with the correct path set), I removed the manual entry and now the new version 11.0.9.11 is automatically discoverd. 

Anyway, I am closing this for now.

Thanks!
