### ISSUE TITLE
Manage symbolic links for JDKs to avoid the need for system restarts

### ISSUE THREAD

**Issue by seanf** [tushev/aojdk-updatewatcher#5]
**Is your feature request related to a problem? Please describe.**
Update Watcher doesn't understand the symbolic link I use to point at the latest JDK, so it thinks I have two copies of Java 8, plus it doesn't help me to keep the symlink up to date automatically. This leads to postponing upgrades.

After updating a JDK, I create a symlink from `C:\Program Files\AdoptOpenJDK\jdk-8.0` to the new installation, eg `C:\Program Files\AdoptOpenJDK\jdk-8.0.275.1-hotspot`. The symlink path `C:\Program Files\AdoptOpenJDK\jdk-8.0` is what I use for the environment variables `JAVA_HOME` and in `PATH` (and in IntelliJ IDEA). 

This symlink scheme ensures that all new invocations of `java` or `javac` will automatically pick up the new JDK, without needing a restart to propagate changes in environment variables. But this scheme doesn't quite fit with Update Watcher yet.

**I'm sure that it's not a 'known-not-a-bug'**
**See**: https://github.com/tushev/aojdk-updatewatcher/wiki/Known-not-a-bugs
[X] Yes

**Describe the solution you'd like**
I would like Update Watcher to understand this symlink scheme, or implement a similar scheme.

Update Watcher would need to understand that the symlink (or junction) and the target directory represent the same JDK installation, and to update the symlink when a new JDK in the same "family" is installed. A family could be Java 8, `most recent LTS`, or `most recent`.

**Describe alternatives you've considered**
A slightly simpler solution: update any symlink which points to the old version of an updated JDK. This is essentially automating what I do manually.

If Update Watcher knows it has just installed an upgrade from version X.Y to X.Z, it could replace a symlink which points to X.Y and make it point to the new installation X.Z. This would probably require some way of registering symlinks (to opt them in for this management), but it might be simpler than managing the concept of JDK families. Any registered symlinks could then be ignored as installations, to avoid having them show up as duplicate installations.

**Additional context**
What I have with my symlink is basically a "junction directory approach" as mentioned in https://github.com/AdoptOpenJDK/openjdk-installer/issues/133, but I think Update Watcher is better placed to solve the problem, since it knows the old and new locations. Also Update Watcher shows all installations, which causes junctions and symlinks to show up as duplicates (at least if they are used in `JAVA_HOME`).

**Comment by tushev** [comment]
Hello, 

Thank you for your suggestion. I agree that this is a good idea, but this kind of things ideally should be managed by installers themselves, alongside with `Set JAVA_HOME` and `Associate .jar` features. Maybe they should have more +1 requests [there](https://github.com/AdoptOpenJDK/openjdk-installer/issues/133).

> Update Watcher is better placed to solve the problem, since it knows the old and new locations.

Actually, the current updater knows absolutely nothing about new location (or even if the installation was successful). All it does is simply re-scan of windows registry to get the list of AdoptOpenJDK installations.

I suppose that the updater is a wrong place for this for two reasons: 1) I prefer UNIX philosophy - `Make each program do one thing well.` and 2) it will require some kind of tracking scheme, which is not easy to develop (see https://github.com/tushev/aojdk-updatewatcher/issues/1#issuecomment-700510346). Besides, what if user has specific requirements, like several installations (of the same branch, but different versions) installed simultaneously? What if something goes wrong with detection (https://github.com/AdoptOpenJDK/openjdk-build/issues/2236)? 

Implementing this in updater would require a robust and universal solution, able to handle all possible cases, which is itself quite an effort. I do not want to take responsibility for it and solve all potential issues.
<br>

Instead, I've added post-install triggers, like this:

![image](https://user-images.githubusercontent.com/18406797/99956411-cbfbd780-2da7-11eb-9549-2fc469abb33f.png)

It may be used for many things, and automating junction directory management is one of them - since the end user knows his scheme and is able to handle all potential conflicts much better than I do.

This functionality will be included in the upcoming release, however, there's no due date yet.

Here a sample PowerShell script to start with:
```
$feature_branch = '8'
$adopt_registry = "Registry::HKLM\Software\AdoptOpenJDK"
# use the following line if you need 32-bit installations
$adopt_registry_x86 = "Registry::HKLM\Software\WOW6432Node\AdoptOpenJDK"

$image_types = Get-ChildItem -Path $adopt_registry
foreach ($type in $image_types) {
    $matching_installations = Get-ChildItem -Path $type.PSPath | Where Name -Like "*\$($feature_branch)*"

    $c = ''
    foreach ($inst in $matching_installations) {
        $c = (Get-ItemProperty (Get-ChildItem -Path $inst.PSPath -Recurse | Where Name -Like '*\MSI*').PSPath).Path
    }

    New-Variable -Force -Name "candidate_$($type.PSChildName)" -Value $c
    Write-Host "The most likely $($type.PSChildName) candidate for $($feature_branch) branch is $($c)"
}
```
It will give you two variables: `candidate_JDK` and `candidate_JRE` (not necessary the highest version ones, just the last encountered in the registry).

**Comment by tushev** [comment]
> Also Update Watcher shows all installations, which causes junctions and symlinks to show up as duplicates (at least if they are used in JAVA_HOME).

As for this, normally this shouldn't be happening. 

In your scheme, I suggest that you turn **Registry Autodiscovery** on and **do not add**  `JAVA_HOME` instance or any other installation manually, it's redundant.

 This way the updater will get only actual "end-point" installations (which should be checked for updates), and not the symlinks.

<hr>  

And if you don't need to check for updates for one of the auto-discovered installations - then (only) you should create a manual override to disable it: https://github.com/tushev/aojdk-updatewatcher/wiki/Types-of-installations#-usage-scenario-disable-updates-check-for-one-of-auto-discovered-installations

**Comment by tushev** [comment]
Just released https://github.com/tushev/aojdk-updatewatcher/releases/tag/2.0.1.0

It implements the post-install scripting functionality: https://github.com/tushev/aojdk-updatewatcher/wiki/Sample-postinstall-scripts and https://github.com/tushev/aojdk-updatewatcher/wiki/%E2%9A%A0-Advanced-configuration
