### ISSUE TITLE
32-bit openj9 installation auto-discovered as "large heap"

### ISSUE THREAD

**Issue by tonibony** [tushev/aojdk-updatewatcher#8]
I have a x64 Windows with installed 32-bit AdoptOpenJDK's "OpenJDK8U-jdk_x86-32_windows_openj9_8u275b01_openj9-0.23.0.msi". That installation was auto-discovered as "large heap". As it's 32-bit, I think it really can only be "normal heap". So, I assumе there is a bug somewhere in the auto-discovery of the heap size.

The incorrect heap size leads to an error when checking for updates for this installation (the checker doesn't find any distribution with the requested parameters). To workaround this, I manually override the auto-discovered heap size to "normal".

<img width="758" alt="heap_size_discovery_bug-aojdk-updatewatcher" src="https://user-images.githubusercontent.com/1815763/103300328-4e129800-4a07-11eb-8203-d4d9c8fe397c.png">

The app version on the affected machine currently is 2.0.2, but it was 2.0.1 when I noticed this problem for the first time.

Interestingly, the app auto-discovered the previous 32-bit JDK 8 installation on the same machine (AdoptOpenJDK's "OpenJDK8U-jdk_x86-32_windows_openj9_8u242b08_openj9-0.18.1.msi") correctly as "normal heap". And successfully updated it to the current version!

**Comment by tushev** [comment]
Hi, 

Please confirm that your `C:\Program Files (x86)\AdoptOpenJDK\jdk-8.0.275.1-openj9\release` file contains

`HEAP_SIZE="Large"`

while it should be `normal`, so this is an bug in AdoptOpenJDK itself, and not my updater.<br>My updater just ultimately trusts that metadata file, if it's available (without metadata, detecting heap size for openj9 is a bit tricky & cumbersome...).

I strongly suggest that you open a ticket in https://github.com/AdoptOpenJDK/openjdk-support/issues (with the data from both your and my posts), because this bug will likely appear in future AdoptOpenJDK/openj9 releases as well...

P.S. While investigating, I also noticed a minor POI in my fallback code (it works when there is no `release` file). 
It was not the cause of this problem, but I will investigate it (and fix if there is a bug there) in the next version. Thank you for your report!

P.P.S. As for `OpenJDK8U-jdk_x86-32_windows_openj9_8u242b08_openj9-0.18.1.msi` - its `release` file does not contain `HEAP_SIZE`, so there just my fallback code was working - and it detected "normal heap" correctly.

**Comment by tonibony** [comment]
> Please confirm that your `C:\Program Files (x86)\AdoptOpenJDK\jdk-8.0.275.1-openj9\release` file contains
> `HEAP_SIZE="Large"`

Confirmed.

> I strongly suggest that you open a ticket in https://github.com/AdoptOpenJDK/openjdk-support/issues (with reference to this issue), because this bug will likely appear in future AdoptOpenJDK/openj9 releases as well, if not fixed...

You're much, much faster than me!

**Comment by tonibony** [comment]
The issue AdoptOpenJDK/openjdk-build/issues/2412 was closed some time ago and the next available release of the problem installation (8.0.292+1) was detected today correctly as "normal heap". The problem is successfully fixed!
